#!/usr/bin/env python3
"""Run the Qwen all-Visit Pattern V2 policy without a tool-timing oracle.

This is a deterministic CPU sensitivity experiment, not the primary live-LLM
result.  The policy is driven through its online API after each completed tool.
Physical tool service is generated by a policy-independent hashed uniform SLO
clock (search/scholar 1--3 seconds; each Visit URL 2--8 seconds); recorded tool
timestamps and ``timing_correction`` fields are never read.  Recorded 0.42x LLM
durations are used only as an environment-side proxy for LLM service and are
not supplied to candidate ranking, admission, or preemption.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import replace
import hashlib
import json
from pathlib import Path
import statistics
import sys
from types import SimpleNamespace
from typing import Any


SCRIPT = Path(__file__).resolve()
REPRODUCTION_ROOT = SCRIPT.parents[1]
REPOSITORY_ROOT = SCRIPT.parents[2]
for import_root in (REPRODUCTION_ROOT, SCRIPT.parent):
    if str(import_root) not in sys.path:
        sys.path.insert(0, str(import_root))

from paste_repro.mapper import write_json_atomic  # noqa: E402
from paste_repro.pattern_v2_all_visit_online import (  # noqa: E402
    DEPLOYABLE_SCHEMA,
    SCHEMA as CROSSFIT_SCHEMA,
    PatternV2CrossFitPredictor,
    PatternV2DeployablePredictor,
    canonical_sha256,
)
from paste_repro.pattern_v2_strict_adapter import (  # noqa: E402
    HashedUniformSLOClock,
    new_hashed_slo_clock_artifact,
)
from paste_repro.strict_trace_runtime import normalize_url  # noqa: E402
from paste_repro.traces import LLMCall, ToolCall, load_sessions  # noqa: E402
from run_pattern_v2_trace_all_visit_shared_capacity import (  # noqa: E402
    Epoch,
    Policy,
    PreparedSession,
    simulate,
)
from run_pattern_v2_trace_all_visit_wall import (  # noqa: E402
    DEFAULT_TRACES,
    executable_url,
    extract_all_visit_decisions,
    visit_urls,
)


RESULT_SCHEMA = "paste_repro.pattern_v2_strict_slo_simulation.v1"
DEFAULT_OUTPUT = (
    REPRODUCTION_ROOT
    / "results"
    / "pattern_v2_strict_slo_simulation"
    / "metrics.json"
)
DEFAULT_CLOCK_SEED_SHA256 = hashlib.sha256(
    b"paste-qwen-pattern-v2-strict-slo-simulation-v1"
).hexdigest()


def _read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON document must be an object: {path}")
    return value


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _load_predictor(path: Path) -> tuple[Any, dict[str, Any]]:
    artifact = _read_json(path)
    if artifact.get("schema") == CROSSFIT_SCHEMA:
        predictor = PatternV2CrossFitPredictor(artifact)
    elif artifact.get("schema") == DEPLOYABLE_SCHEMA:
        predictor = PatternV2DeployablePredictor(artifact)
    else:
        raise ValueError("unsupported Pattern V2 predictor artifact schema")
    return predictor, artifact


def _role_ids(path: Path | None, role: str | None) -> set[str] | None:
    if path is None and role is None:
        return None
    if path is None or role is None:
        raise ValueError("split manifest and evaluation role must be supplied together")
    if role not in {"calibration", "tuning", "final"}:
        raise ValueError("evaluation role must be calibration, tuning, or final")
    manifest = _read_json(path)
    rows = manifest.get(f"{role}_sessions")
    if not isinstance(rows, list) or not rows:
        raise ValueError(f"split manifest has no {role} sessions")
    result = {
        str(row["session_id"])
        for row in rows
        if isinstance(row, Mapping) and isinstance(row.get("session_id"), str)
    }
    if len(result) != len(rows):
        raise ValueError(f"split manifest has malformed or duplicate {role} roots")
    return result


def _tool_service_s(clock: HashedUniformSLOClock, event: ToolCall) -> float:
    """Environment service without touching an event timing field."""

    if event.tool_name == "visit":
        return sum(
            clock.service_s(
                tool_name="visit",
                tool_arguments={"url": normalized},
            )
            for url in visit_urls(event)
            if executable_url(normalized := normalize_url(url))
        )
    return clock.service_s(
        tool_name=event.tool_name,
        tool_arguments=event.tool_args,
    )


def build_prepared_sessions(
    *,
    traces: Path,
    predictor: Any,
    clock: HashedUniformSLOClock,
    evaluation_ids: set[str] | None = None,
) -> tuple[tuple[PreparedSession, ...], dict[str, Any]]:
    """Materialize simulator DTOs through only the online predictor boundary."""

    all_sessions = load_sessions(traces)
    sessions = tuple(
        session
        for session in all_sessions
        if evaluation_ids is None or session.session_id in evaluation_ids
    )
    if evaluation_ids is not None and {
        session.session_id for session in sessions
    } != evaluation_ids:
        missing = sorted(evaluation_ids - {session.session_id for session in sessions})
        raise ValueError(f"evaluation roots are absent from trace directory: {missing}")
    decisions = extract_all_visit_decisions(sessions)
    decisions_by_session: dict[str, list[Any]] = defaultdict(list)
    for decision in decisions:
        decisions_by_session[decision.session_id].append(decision)

    prepared: list[PreparedSession] = []
    authority_urls = 0
    cache_hits = 0
    emitted = 0
    unique_candidates = 0
    llm_proxy_s = 0.0
    generated_tool_service_s = 0.0

    for session in sessions:
        # Reconstruct a contiguous counterfactual timeline.  Only LLMCall's
        # public proxy duration is consumed; no ToolCall timestamp or timing
        # correction is accessed here or below.
        cursor_s = 0.0
        starts: dict[int, float] = {}
        ends: dict[int, float] = {}
        for event_index, event in enumerate(session.events):
            if isinstance(event, LLMCall):
                starts[event_index] = cursor_s
                cursor_s += float(event.total_time_s)
                llm_proxy_s += float(event.total_time_s)
                ends[event_index] = cursor_s
            elif isinstance(event, ToolCall):
                starts[event_index] = cursor_s
                service_s = _tool_service_s(clock, event)
                generated_tool_service_s += service_s
                cursor_s += service_s
                ends[event_index] = cursor_s

        online = predictor.start_session(
            source_session_id=session.session_id,
            runtime_session_id=f"strict-slo-sim:{session.session_id}",
        )
        session_cache: set[str] = set()
        epochs: list[Epoch] = []
        for decision in sorted(
            decisions_by_session.get(session.session_id, ()),
            key=lambda row: row.trigger_event_index,
        ):
            trigger = session.events[decision.trigger_event_index]
            if not isinstance(trigger, ToolCall):
                raise RuntimeError("Pattern V2 decision trigger is not a tool")
            if not decision.lead_llm_event_indices:
                raise RuntimeError("Pattern V2 decision has no causal lead LLM")
            lead_index = decision.lead_llm_event_indices[0]
            lead = session.events[lead_index]
            if not isinstance(lead, LLMCall):
                raise RuntimeError("Pattern V2 lead event is not an LLM")
            predictions = online.predict_after_tool(
                tool_name=trigger.tool_name,
                tool_arguments=trigger.tool_args,
                current_messages=lead.messages,
            )
            candidates = tuple(
                SimpleNamespace(
                    exact_probability=float(row.confidence),
                    pattern=SimpleNamespace(
                        url=normalize_url(row.url),
                        position=int(row.source_position),
                    ),
                )
                for row in predictions
            )
            if len(candidates) > 10:
                raise RuntimeError("online Pattern V2 exceeded fixed Top-10")
            emitted += len(candidates)
            for candidate in candidates:
                if candidate.pattern.url not in session_cache:
                    session_cache.add(candidate.pattern.url)
                    unique_candidates += 1
            candidate_services = tuple(
                clock.service_s(
                    tool_name="visit",
                    tool_arguments={"url": candidate.pattern.url},
                )
                for candidate in candidates
            )

            targets = tuple(
                normalize_url(url)
                for url in decision.authoritative_urls
                if executable_url(url)
            )
            services = tuple(
                clock.service_s(
                    tool_name="visit", tool_arguments={"url": url}
                )
                for url in targets
            )
            authority_urls += len(targets)
            cache_hits += sum(url in session_cache for url in targets)
            original_start_s = starts[lead_index]
            if decision.outcome == "visit":
                target_index = decision.target_tool_event_index
                if target_index is None or target_index not in starts or target_index not in ends:
                    raise RuntimeError("Visit target lacks generated timeline bounds")
                authority_offset_s = starts[target_index] - original_start_s
                baseline_authority_done_s = ends[target_index]
            else:
                authority_offset_s = None
                baseline_authority_done_s = None
                targets = ()
                services = ()
            epochs.append(
                Epoch(
                    decision_id=decision.decision_id,
                    original_start_s=original_start_s,
                    authority_offset_s=authority_offset_s,
                    baseline_authority_done_s=baseline_authority_done_s,
                    targets=targets,
                    services_s=services,
                    candidates=candidates,
                    candidate_services_s=candidate_services,
                )
            )
        prepared.append(
            PreparedSession(
                session_id=session.session_id,
                full_wall_s=cursor_s,
                epochs=tuple(epochs),
            )
        )

    inventory = {
        "independent_sessions": len(prepared),
        "prediction_windows": len(decisions),
        "emitted_predictions": emitted,
        "unique_session_url_candidates": unique_candidates,
        "authority_visit_urls": authority_urls,
        "policy_cache_hit_occurrences": cache_hits,
        "policy_cache_hit_rate": cache_hits / authority_urls if authority_urls else 0.0,
        "llm_trace_proxy_service_s": llm_proxy_s,
        "hashed_slo_generated_tool_service_s": generated_tool_service_s,
        "recorded_tool_timing_fields_read": False,
    }
    return tuple(prepared), inventory


def _mean(rows: Sequence[Mapping[str, Any]], key: str) -> float:
    return statistics.fmean(float(row[key]) for row in rows)


def run_curve(
    sessions: Sequence[PreparedSession],
    *,
    workload_replicas: int,
    visit_capacity: int,
    concurrencies: Sequence[int],
    repetitions: int,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    workload = tuple(
        replace(session, session_id=f"replica-{replica}:{session.session_id}")
        for replica in range(workload_replicas)
        for session in sessions
    )
    treatment_policy = Policy(
        "strict_probability_top10",
        "fixed_top10",
        "adaptive_idle_fill",
    )
    curve: list[dict[str, Any]] = []
    raw: dict[str, Any] = {}
    for concurrency in concurrencies:
        baseline_runs: list[dict[str, Any]] = []
        treatment_runs: list[dict[str, Any]] = []
        paired: list[dict[str, float]] = []
        for seed in range(repetitions):
            baseline = simulate(
                workload,
                policy=None,
                visit_capacity=visit_capacity,
                offered_concurrency=concurrency,
                seed=seed,
            )
            treatment = simulate(
                workload,
                policy=treatment_policy,
                visit_capacity=visit_capacity,
                offered_concurrency=concurrency,
                seed=seed,
            )
            baseline_runs.append(baseline)
            treatment_runs.append(treatment)
            paired.append(
                {
                    "e2e_speedup_fraction": 1.0
                    - treatment["makespan_s"] / baseline["makespan_s"],
                    "mean_flow_speedup_fraction": 1.0
                    - treatment["mean_flow_s"] / baseline["mean_flow_s"],
                    "tool_stall_reduction_fraction": 1.0
                    - treatment["authority_exposed_s"]
                    / baseline["authority_exposed_s"],
                }
            )
        row = {
            "concurrency": concurrency,
            "baseline_makespan_s": _mean(baseline_runs, "makespan_s"),
            "treatment_makespan_s": _mean(treatment_runs, "makespan_s"),
            "e2e_speedup_fraction": _mean(paired, "e2e_speedup_fraction"),
            "mean_flow_speedup_fraction": _mean(
                paired, "mean_flow_speedup_fraction"
            ),
            "tool_stall_reduction_fraction": _mean(
                paired, "tool_stall_reduction_fraction"
            ),
            "realized_cache_hit_rate": _mean(
                treatment_runs, "realized_cache_hit_rate"
            ),
            "call_amplification": _mean(treatment_runs, "call_amplification"),
            "physical_speculative_starts": _mean(
                treatment_runs, "physical_speculative_starts"
            ),
            "wasted_speculative_starts": _mean(
                treatment_runs, "wasted_speculative_starts"
            ),
            "preempted_speculations": _mean(
                treatment_runs, "preempted_speculations"
            ),
        }
        curve.append(row)
        raw[str(concurrency)] = {
            "baseline": baseline_runs,
            "treatment": treatment_runs,
            "paired": paired,
        }
    return curve, {
        "workload_instances": len(workload),
        "raw_runs": raw,
    }


def _render_report(payload: Mapping[str, Any]) -> str:
    inventory = payload["inventory"]
    lines = [
        "# Strict Pattern V2 hashed-SLO CPU sensitivity",
        "",
        "This is a deterministic systems sensitivity replay, not a live-LLM or "
        "autonomous-agent result. Candidate inference is online and causal. Tool "
        "service comes only from the sealed normalized-invocation hashed SLO clock; "
        "recorded trace tool durations are never read. Recorded 0.42x LLM durations "
        "are environment-only proxy service and never enter the policy.",
        "",
        f"Policy coverage: {inventory['policy_cache_hit_occurrences']}/"
        f"{inventory['authority_visit_urls']} = "
        f"{inventory['policy_cache_hit_rate']:.2%}.",
        "",
        "| C | Realized hit | Tool stall reduction | E2E speedup | Mean-flow speedup | Call amp. |",
        "|---:|---:|---:|---:|---:|---:|",
    ]
    for row in payload["curve"]:
        lines.append(
            f"| {row['concurrency']} | {row['realized_cache_hit_rate']:.2%} "
            f"| {row['tool_stall_reduction_fraction']:.2%} "
            f"| {row['e2e_speedup_fraction']:.2%} "
            f"| {row['mean_flow_speedup_fraction']:.2%} "
            f"| {row['call_amplification']:.3f}x |"
        )
    lines.extend(
        [
            "",
            "All loads use the same probability Top-10 policy, session URL "
            "infinite cache, 64-slot shared Visit pool, adaptive idle fill, exact "
            "in-flight promotion, and lowest-probability preemption for authority.",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--traces", type=Path, default=DEFAULT_TRACES)
    parser.add_argument("--predictor-artifact", type=Path, required=True)
    parser.add_argument("--split-manifest", type=Path)
    parser.add_argument(
        "--evaluation-role", choices=["calibration", "tuning", "final"]
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--visit-capacity", type=int, default=64)
    parser.add_argument("--workload-replicas", type=int, default=2)
    parser.add_argument("--repetitions", type=int, default=16)
    parser.add_argument(
        "--concurrencies",
        type=int,
        nargs="+",
        default=[1, 2, 4, 8, 16, 32, 48, 64, 96, 128],
    )
    parser.add_argument(
        "--clock-seed-sha256", default=DEFAULT_CLOCK_SEED_SHA256
    )
    args = parser.parse_args()
    if args.visit_capacity != 64:
        parser.error("the frozen Pattern V2 setup requires visit-capacity=64")
    if args.workload_replicas <= 0 or args.repetitions <= 0:
        parser.error("replicas and repetitions must be positive")
    if any(value <= 0 for value in args.concurrencies):
        parser.error("concurrencies must be positive")
    return args


def main() -> None:
    args = parse_args()
    predictor, predictor_artifact = _load_predictor(args.predictor_artifact)
    evaluation_ids = _role_ids(args.split_manifest, args.evaluation_role)
    clock_artifact = new_hashed_slo_clock_artifact(
        seed_sha256=args.clock_seed_sha256
    )
    clock = HashedUniformSLOClock(clock_artifact)
    sessions, inventory = build_prepared_sessions(
        traces=args.traces,
        predictor=predictor,
        clock=clock,
        evaluation_ids=evaluation_ids,
    )
    curve, run_details = run_curve(
        sessions,
        workload_replicas=args.workload_replicas,
        visit_capacity=args.visit_capacity,
        concurrencies=args.concurrencies,
        repetitions=args.repetitions,
    )
    payload: dict[str, Any] = {
        "schema": RESULT_SCHEMA,
        "experiment_kind": "cpu_discrete_event_sensitivity_not_live_llm",
        "evaluation_regime": predictor_artifact["evaluation_regime"],
        "claim_scope": predictor_artifact.get(
            "claim_scope", "retrospective_crossfit"
        ),
        "prior_policy_development_used_evaluation_corpus": (
            predictor_artifact.get("prior_policy_development_used_evaluation_corpus")
        ),
        "predictor_artifact_sha256": predictor.artifact_sha256,
        "predictor_file_sha256": _file_sha256(args.predictor_artifact),
        "physical_service_clock": clock_artifact,
        "policy_can_read_physical_clock_seed": False,
        "policy_reads_llm_trace_duration": False,
        "policy_reads_tool_trace_duration": False,
        "environment_llm_service": "recorded_x0.42_trace_total_time_proxy",
        "environment_tool_service": "normalized_invocation_hashed_uniform_SLO",
        "visit_capacity": args.visit_capacity,
        "speculative_cap": args.visit_capacity,
        "workload_replicas": args.workload_replicas,
        "repetitions": args.repetitions,
        "inventory": inventory,
        "curve": curve,
        **run_details,
    }
    payload["result_sha256"] = canonical_sha256(payload)
    write_json_atomic(args.output, payload)
    report_path = args.output.with_name("REPORT.md")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(_render_report(payload), encoding="utf-8")
    print(f"metrics={args.output.resolve()}")
    print(f"report={report_path.resolve()}")
    print(f"result_sha256={payload['result_sha256']}")
    for row in curve:
        print(
            f"C={row['concurrency']} hit={row['realized_cache_hit_rate']:.2%} "
            f"tool={row['tool_stall_reduction_fraction']:.2%} "
            f"e2e={row['e2e_speedup_fraction']:.2%}"
        )


if __name__ == "__main__":
    main()
